### ISSUE TITLE
Seeing 'pyscript.app_config' is not defined

### ISSUE THREAD

**Issue by polds** [SiriosDev/SwitchBot-API-Script-Caller#14]
Hey, I've just configured this caller and have pyscript setup. When I try to call refresh_devices I see the below error. 

I'm pretty sure I've got the `!include` to pull in the config correctly so am not entirely sure what I'm missing.

Do you have any ideas?

```
2023-02-03 19:11:52.204 ERROR (MainThread) [custom_components.pyscript.file.switchbot.switchbot_refresh_devices] Exception in <file.switchbot.switchbot_refresh_devices> line 106:
        headers_dict=auth(**pyscript.app_config)
                            ^
NameError: name 'pyscript.app_config' is not defined
```

**Comment by polds** [comment]
Nevermind. I had not put it in `pyscript/apps/` and only in `pyscript`. It works.

**Comment by beber-msft** [comment]
Hello, I am having the same issue. However when moving the script into pyscript/apps instead of pyscript, Homeassistant is not detecting the scripts anymore. How can I fix this?

**Comment by SiriosDev** [comment]
if you have followed the steps step by step, there should be no errors, however, I understand that it might not be crystal clear, so to help you I ask you to tell me the full path to `pyscript/apps`, and your `configuration.yaml` file (with due censorship on sensitive data)

**Comment by beber-msft** [comment]
Hello,
this is my Pyscript section of `configuration.yaml`:
```yaml
pyscript:
  allow_all_imports: true
  hass_is_global: true
```

Full path to `pyscript\apps` is:
`config\pyscript\apps`

I guess there is a specific reference missing to that directory in pyscript config?

Appreciate your help.

**Comment by SiriosDev** [comment]
I took the liberty of editing your comment to read it better

**Comment by SiriosDev** [comment]
btw
In `configuration.yaml` there should be:
```yaml
pyscript: !include pyscript/config.yaml
```
or
```yaml
pyscript:
  allow_all_imports: true
  apps:
    switchbot: !include /config/SwitchBot-API-Script-Caller/pyscript/switchbot.yaml
```
If you want it to be compatible with the upgrade method

**Comment by beber-msft** [comment]
thank you, this did solve it. appreciate your support.
