### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by havy1601** [SiriosDev/SwitchBot-API-Script-Caller#15]
Hi,

looks like there is a typo in your switchbot.py.
Currently the custom commands are not woring with your integration.

You need to change following from custom to customize:

![image](https://user-images.githubusercontent.com/97604784/219906736-ee369a16-62a4-4f1d-9d3d-458d55816fee.png)

Or you could also change your predefined options for the Switchbot Generic Command from 
customize to custom.

And also thank you very much for the integration, helped me alot! 👍 :)

Br Adrian

**Comment by SiriosDev** [comment]
Wait, I am not clear about one thing, what was written before and what did you write?

Edit: Ah yes I got it (you could have given me a PR) anyway no problem I'll fix it right away
