### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by labaland** [SiriosDev/SwitchBot-API-Script-Caller#24]
Hi i cant get HA to get the  "switch.switchbot_remote_<device_name>"

This is how i installed this.

I could not find this in HACS and custom repistories did not work so i downloaded the zip from here and put the "SwitchBot-API-Script-Caller" folder in Homeassistant map  "config"

I think im doing wrong at this step:

```
# use `mkdir -p /config/pyscript/apps/` if the directory doesn't exist
cd /config/pyscript/apps/

# Create a symbolic link to the apps directory named switchbot
ln -s /config/SwitchBot-API-Script-Caller/pyscript/apps/switchbot.py switchbot.py
```

How do i do that in docker-compose.yaml? i have a synology nas. this is my dockercompose fpr homeassistant;

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
      - /run/dbus:/run/dbus:ro
      - /volume3/docker/homeassistant:/config
      - /volume3/docker/homeassistant/SwitchBot-API-Script-Caller/pyscript/apps/:/config/pyscript/apps/
    environment:
      - TZ=Europe/Stockholm
Please help teally want to use my ir devices in homeassistant ! :)

**Comment by SiriosDev** [comment]
this repository is not "compatible" with hacs because it is a pyscrypt, not a Python script, from hacs you have to download only the pyscript integration, and then follow the step by step guide

**Comment by SiriosDev** [comment]
the `config` folder is the one in which inside you find your `configuration.yaml` file

**Comment by labaland** [comment]
yes that is the config yes.
1
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/9c67ade8-9784-43ae-9172-8c30b672a76b)
,2
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/c8b01c57-3eaa-4a11-a9b2-cfb24772c42e)

,
secrets i added in Homeassistants secrets.yaml,
,3
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/1c40259b-f831-4f99-8eed-639ba94b639a)
,,4
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/67d8fb22-73fc-448f-ad91-64bdcde78c89)

Anything wrong you see?

And when i restart ha  i get this notification:
The following integrations and platforms could not be set up:
[switchbot](https://www.home-assistant.io/integrations/switchbot) 

Thanks for answering me! :)

**Comment by SiriosDev** [comment]
I don't understand what docker has to do with it, the actions of the guides should be done starting from the folder that contains, `configuration.yaml`, `secret.yaml`, `automation.yaml` etc.

**Comment by SiriosDev** [comment]
wait, from now on, I ask you a question you give me an answer

**Comment by SiriosDev** [comment]
1) Did you install the pyscript integration from hacs?

**Comment by labaland** [comment]
> I don't understand what docker has to do with it, the actions of the guides should be done starting from the folder that contains, `configuration.yaml`, `secret.yaml`, `automation.yaml` etc.

I thought linking the files was on the server and not in ha hehe..

> wait, from now on, I ask you a question you give me an answer

Yes!

> 1. Did you install the pyscript integration from hacs?

Yes i did! :)


Is my folder/file setup correct? 
Thank you !



i dont understand step 4.

**_# use `mkdir -p /config/pyscript/apps/` if the directory doesn't exist
cd /config/pyscript/apps/¨_**

i created thjeese 2 folders "/pyscript/apps/"


 _**# Create a symbolic link to the apps directory named switchbot
ln -s /config/SwitchBot-API-Script-Caller/pyscript/apps/switchbot.py switchbot.py**_

This i was guessing is outside ha? in terminal? i dont know how to do that on a synology nas. must be in docker?? :)

**Comment by SiriosDev** [comment]
> Is my folder/file setup correct?

99% wrong

**Comment by SiriosDev** [comment]
back to the questions
2. did you clone the repository as written in the guide?

**Comment by labaland** [comment]
> back to the questions 2) did you clone the repository as written in the guide?

i downloaded the zip file. and used the files from there


my discord username is "labaland#1503" im in ha discord too if u want to help me faster :) if u want only :)

**Comment by SiriosDev** [comment]
you have to follow the steps in the guide, not download zipper or anything else

**Comment by SiriosDev** [comment]
custom procedures have too many things to check, help is only related to guide steps, or post installation problems

**Comment by labaland** [comment]
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/de65bb10-3dbe-42e6-a167-74cae8a5f401)

putty

**Comment by SiriosDev** [comment]
just to be sure, `homeassiant` is your configuration folder, yes?

**Comment by labaland** [comment]
> just to be sure, `homeassiant` is your configraztion folder, yes?

Yes it is! 
Downloaded git server. Now i could use "git clone https://github.com/SiriosDev/SwitchBot-API-Script-Caller.git" :D

**Comment by SiriosDev** [comment]
perfect

**Comment by SiriosDev** [comment]
now follow the guide and in case of errors I am here

**Comment by labaland** [comment]
> now follow the guide and in case of errors I am here

Yes thanks! I will try now from beginning =)

**Comment by labaland** [comment]
Ok step 1 works, really not sure about step 2 see below.

3. added my api and key in secrets.yalm and used https://www.uuidgenerator.net/version4 to make a uuid like "867e72d6-f1b9-5g83-acb0-2b8586591bb3"

4. created 2 folders pyscript & apps. Insiden HA config folder like:  HAconfig.../pyscript/apps/

Then i used this command "ln -s /config/SwitchBot-API-Script-Caller/pyscript/apps/switchbot.py switchbot.py" without any errors.

Rebooted ha and did not get any enteties and the deafault switchbot integration fails to run. Should i remove that one ? 


STEP 2:
I dont have any config.yaml file in  "HAconfig.../pyscript/config.yaml"

I really dont understand step 2. Should i creat a config.yaml there and add this to it?:
allow_all_imports: true
apps:
 switchbot: !include /config/SwitchBot-API-Script-Caller/pyscript/switchbot.yaml

or do you mean HomeAssistant's own configuration.yaml?

sry, and sry for not very good english! :D

**Comment by labaland** [comment]
> now follow the guide and in case of errors I am here

Ok step 1 works, really not sure about step 2 see below.

added my api and key in secrets.yalm and used https://www.uuidgenerator.net/version4 to make a uuid like "867e72d6-f1b9-5g83-acb0-2b8586591bb3"

created 2 folders pyscript & apps. Insiden HA config folder like: HAconfig.../pyscript/apps/

Then i used this command "ln -s /config/SwitchBot-API-Script-Caller/pyscript/apps/switchbot.py switchbot.py" without any errors.

Rebooted ha and did not get any enteties and the deafault switchbot integration fails to run. Should i remove that one ?

STEP 2:
I dont have any config.yaml file in "HAconfig.../pyscript/..

I really dont understand step 2. Should i create a config.yaml there and add this to it?:
allow_all_imports: true
apps:
switchbot: !include /config/SwitchBot-API-Script-Caller/pyscript/switchbot.yaml

or do you mean HomeAssistant's own configuration.yaml?

sry, and sry for not very good english! :D

**Comment by SiriosDev** [comment]
> Should i remove that one ?

Nope

**Comment by SiriosDev** [comment]
>sry, and sry for not very good english!

neither me! I'm Italian 😅

**Comment by SiriosDev** [comment]
so, can you post screen off homeassiant and pyscript folders?

**Comment by labaland** [comment]
> so, can you post screen off homeassiant and pyscript folders?

Haha i see! here it is =)  pretty much the same i guess

step 1:
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/4586860f-e68d-406f-8cb5-c2d759d30fb7)

step 2:
No config file there, should i creat one and add that?
i think i  got this wrong. i should not make a pyscript folder in ha config folder??? i made that one

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/6489a14d-3a78-4a9e-a406-31153b7bfec8)

step 3:
all added: 
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/f89a0dd8-0240-4991-a88e-e05bb196f808)

step 4: in putty
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/0820acc5-ca52-42c5-ae14-b3cd8b44212b)

**Comment by labaland** [comment]
This i dont understand:

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/d05a6c68-87c6-45b1-914c-64696244033e)

under the switchbot section?? i added mine thru ui i dont have it in my configuration.yaml. i have the hub

**Comment by labaland** [comment]
This is already there: 
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/2abeb8d5-15e9-4738-8778-59a52be8a603)

**Comment by SiriosDev** [comment]
> This is already there: ![image](https://user-images.githubusercontent.com/20958435/239713301-2abeb8d5-15e9-4738-8778-59a52be8a603.png)

ignore this file

**Comment by labaland** [comment]
> > This is already there: ![image](https://user-images.githubusercontent.com/20958435/239713301-2abeb8d5-15e9-4738-8778-59a52be8a603.png)
> 
> ignore this file

Did u see pictures above? :) 21min ago

**Comment by SiriosDev** [comment]
> ![image](https://user-images.githubusercontent.com/20958435/239713099-6489a14d-3a78-4a9e-a406-31153b7bfec8.png)

in this folder☝️, you have to create a config.yaml file and paste these code.

```yaml
allow_all_imports: true
apps:
 switchbot: !include /config/SwitchBot-API-Script-Caller/pyscript/switchbot.yaml
```

you have to have something like this:

```bash
homeassiant/
└── pyscrpt/
    ├── apps/
    └── config.yaml
other your files
configuration.yaml

```

---

you didn't have it because you didn't finish "installing" pyscript (procedure on their hacs page/repo)
_I guess you haven't even "activated" pyscript yet by entering the string in confiuration.yaml (`pyscript: !include pyscript/config.yaml`)_

**Comment by labaland** [comment]
> 

i created config.yaml now in homeassistant/pyscript/config.yaml wwith that text.

it looks this:
```
homeassiant/
  └── pyscrpt/
      ├── apps/
      └── config.yaml
  └── SwitchBot-API-Script-Caller
      ├── .git
      ├── .github
      ├── pyscript
          ├── apps
          └── config.yaml
          └── switchbot.yaml
  └── configuration.yaml
```


added this in configuration.yaml:
"pyscript: !include pyscript/config.yaml"

rebooted and no new entities, guess i have to do the refresh thing ?

should i make a switch for each ir device or will this make me them?

BTW i have the SwitchBot Hub Mini and a bluetooth proxy esp32

this integration adds both my Curtain and self added ir devices?

**Comment by labaland** [comment]
Now i have the services in home assistant! Thank YOU so much for helping me this much! Hope it will help another noob like me too!

I got my infrared devices but not like my courtain.? The regular switchbot integration fails at ha boot now 🤔 

I think i have to use SwitchBot Generic Command for that! (*edit* nope? i dont get a entity for it so cant use custom command?) 

thanks!!! 😍

**Comment by SiriosDev** [comment]
> Now i have the services in home assistant! Thank YOU so much for helping me this much! Hope it will help another noob like me too!

great!


> I got my infrared devices but not like my courtain.? 

I didn't understand this question 😅

> The regular switchbot integration fails at ha boot now 🤔

I don't know, the official integration uses a different method of connection, so they can't affect each other

---

in any case, "easy" curtain management will come with the next version, until then, they will be generated as switch entities that can be used with generic command

**Comment by labaland** [comment]
> 

Okey it started after i added this integration :P
Hmm i did not get any switch for my curtain.
Ok sweet! i wait for the update then and use api calls til then =)

**Comment by labaland** [comment]
> I don't know, the official integration uses a different method of connection, so they can't affect each other

Theese are the errors in the log after i added this :) :

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/a0dd9741-9ea6-4a88-9b78-c9deabc38965)

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/91cec430-3318-43a6-ae20-4ed85035d2fe)

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/5e8481d3-f616-471d-ad2e-6daf8a9d8462)

**Comment by SiriosDev** [comment]
I repeat, it is not my problem, the official integration uses the Bluetooth API, my script uses the http request API. You must have modified it to something you shouldn't have

**Comment by labaland** [comment]
> I repeat, it is not my problem, the official integration uses the Bluetooth API, my script uses the http request API. You must have modified it to something you shouldn't have

i have not change anything.  Now i deleted the 2 folders SwitchBot-API-Script-Caller & pyscript from HA config folder and restarted then i got this when ha started : 
Then it works.. wierd :/ 
![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/b7a05bff-ba4c-4f4e-87e8-e9e90a464a48)

**Comment by SiriosDev** [comment]
This makes no sense, they are two completely different things, the only thing in common is the fiscal object

**Comment by labaland** [comment]
> 

ok :/ 

Now i tested to only add back the folder "SwitchBot-API-Script-Caller"  and not script pyscript, and no "pyscript: !include pyscript/config.yaml" in comfiguration.yaml

Then integration fails again. so something in that folder i guess?? 😆

**Comment by labaland** [comment]
> This makes no sense, they are two completely different things, the only thing in common is the fiscal object

Are you using both ? :)

**Comment by SiriosDev** [comment]
> > 
> 
> ok :/
> 
> Now i tested to only add back the folder "SwitchBot-API-Script-Caller" and not script pyscript, and no "pyscript: !include pyscript/config.yaml" in comfiguration.yaml
> 
> Then integration fails again. so something in that folder i guess?? 😆

this is impossible because just the `SwitchBot-API-Script-Caller` folder without pyscript doesn't do anything, it's like it's not there

**Comment by labaland** [comment]
yeah okey, very wierd :P

**Comment by labaland** [comment]
> > > 
> > 
> > 
> > ok :/
> > Now i tested to only add back the folder "SwitchBot-API-Script-Caller" and not script pyscript, and no "pyscript: !include pyscript/config.yaml" in comfiguration.yaml
> > Then integration fails again. so something in that folder i guess?? 😆
> 
> this is impossible because just the `SwitchBot-API-Script-Caller` folder without pyscript doesn't do anything, it's like it's not there

okey, very wierd :P

But "pyscript" in pic above is in the error message. so must be some kind of conflict? i have no idea.  i wait for update then =) 

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/4d535dd4-b748-40e5-a105-05283002f259)

![image](https://github.com/SiriosDev/SwitchBot-API-Script-Caller/assets/20958435/76ce2758-3a0c-42bb-a1ba-211fa83ce040)

**Comment by labaland** [comment]
@SiriosDev 
Found this thread now https://github.com/SiriosDev/SwitchBot-API-Script-Caller/issues/23#issuecomment-1438884356
Is it a "beta" version where curtains work?
Is it possible to download it?

**Comment by SiriosDev** [comment]
yes there is but it is not yet ready, you can use it, but without in-depth programming knowledge it will not work

**Comment by labaland** [comment]
okey i understand =)

**Comment by labaland** [comment]
@SiriosDev 
My last quiestion, & thank you for helping me so much to get this working!
It is not possible what i understand to see the state on my airconditioner/IR HVAC? so i know the service call did work? Like i can see in the switchbot app?

**Comment by SiriosDev** [comment]
> @SiriosDev 
> My last quiestion, & thank you for helping me so much to get this working!
> It is not possible what i understand to see the state on my airconditioner/IR HVAC? so i know the service call did work? Like i can see in the switchbot app?
> 

Next version 😉

**Comment by labaland** [comment]
Cant wait :D

**Comment by labaland** [comment]
@SiriosDev 
Hi! Is it possible that you can add "swing" to hvac/aircon service call ?  :)

**Comment by SiriosDev** [comment]
Nope, unfortunately is not supported by the Switchbot API, the only way is to take advantage of a custom remote control, and the generic command

**Comment by labaland** [comment]
ahh okey!  Then i will use that =)

When do you think next update will be? or is it not possible to say :P

**Comment by SiriosDev** [comment]
I think around August, now I'm busy with the university.

**Comment by labaland** [comment]
@SiriosDev 
Hi again! 
Im setting up a rpi with Home assistant to a friend at my home, and it can find my switchbot courtain.
If u remember as above my ha switchbot integration failed/got errors after i installed this api caller. So must be something.
¨
If u want i can set it up on the pi also to see if the arror appears there also.

Thanks! :)

**Comment by SiriosDev** [comment]
try and let me know

**Comment by SiriosDev** [comment]
But I am still in the midst of university exams so it still takes a while for the new update

**Comment by labaland** [comment]
@SiriosDev The new HA update gave me back Switchbot curatin bluetooth again :P 
Btw, This integration with Aircon works amazing! Never fails a single time 👍 :)

**Comment by SiriosDev** [comment]
I said it myself that the errors were not related to this script. HVAC work by no doubt, it is the only one I can physically test, in fact the first version was only generic and hvac everything else is thanks to two guys (the second of the two will be seen in the next update)

**Comment by labaland** [comment]
@SiriosDev Hi! again! :)
Im sad to read that this will be discontinued, But why? Can i control my Airconditioner with official integration? i dont see anything on the docs here : https://www.home-assistant.io/integrations/switchbot/

*edit* i found it, SwitchBot Cloud..
But still, thank you for making this

**Comment by SiriosDev** [comment]
As you said, on Switch bot cloud integration work, but it's not fully working, turn on/off is still in a separated entity and some modality is not "starting"
